### ISSUE TITLE
Server stuck on loading screen

### ISSUE THREAD

**Issue by HAVOCWIZARD** [Firstyminator/ArmA3_Wasteland.Altis#1]
Hey

i thank you for all the work that you have done, i installed a fresh install from scratch, " windows". i compile the mission file as is and activated the logs...all looks great and it loads everything nicely. but i keep on staying on the loading screen after the mission download, i looked at the rpt and found a bug...

here is a snipped of the code...the problem is marked with *************

"[INFO] A3W weatherSaving = ON"
"[INFO] A3W hcObjSaving = OFF"
"A3Wasteland - world persistence loaded 0 objects from iniDBI"
"A3Wasteland - world persistence loaded 0 vehicles from iniDBI"
"[INFO] A3W loot spawning is ENABLED"
"WASTELAND SERVER - Initializing Server Spawning"
"-- LOOTSPAWNER initialise ------------------------"
"-- LOOTSPAWNER spawnBuilding_list ready, d: 0s"
"Creating territory capture trigger for 'TERRITORY_SW_AIRFIELD'"
"Creating territory capture trigger for 'TERRITORY_MAIN_AIRBASE_SW'"
"Creating territory capture trigger for 'TERRITORY_MAIN_AIRBASE_CENTER'"
"Creating territory capture trigger for 'TERRITORY_MAIN_AIRBASE_NE'"
"Creating territory capture trigger for 'TERRITORY_NW_AIRFIELD'"
"Creating territory capture trigger for 'TERRITORY_NE_AIRFIELD'"
"Creating territory capture trigger for 'TERRITORY_SE_AIRFIELD'"
"Creating territory capture trigger for 'TERRITORY_WEST_POWER_PLANT'"
"Creating territory capture trigger for 'TERRITORY_SALTFLATS_AIRFIELD'"
"Creating territory capture trigger for 'TERRITORY_THRONOS_CASTLE'"
"WARNING: No config_territory_markers definition for marker 'TERRITORY_KASTRO_CASTLE'. Deleting it!"
"Creating territory capture trigger for 'TERRITORY_CENTER_POWER_PLANT'"
"Creating territory capture trigger for 'TERRITORY_IRAKLIA_RUINS'"
"Creating territory capture trigger for 'TERRITORY_ARTINARKI_RUINS'"
"Creating territory capture trigger for 'TERRITORY_MAGOS_TRANSMITTER'"
"Creating territory capture trigger for 'TERRITORY_PYRSOS_TRANSMITTER'"
"Creating territory capture trigger for 'TERRITORY_MILITARY_RESEARCH'"
"Creating territory capture trigger for 'TERRITORY_6_DOCKS_A'"
"Creating territory capture trigger for 'TERRITORY_6_DOCKS_B'"
"Creating territory capture trigger for 'TERRITORY_6_DOCKS_C'"
"Creating territory capture trigger for 'TERRITORY_6_DOCKS_D'"
"Creating territory capture trigger for 'TERRITORY_0_KAVALA_B'"
"Creating territory capture trigger for 'TERRITORY_0_KAVALA_A'"
"Creating territory capture trigger for 'TERRITORY_0_KAVALA_C'"
"WARNING: No config_territory_markers definition for marker 'TERRITORY_1_ALTISAIR_A'. Deleting it!"
"WARNING: No config_territory_markers definition for marker 'TERRITORY_1_ALTISAIR_B'. Deleting it!"
"WARNING: No config_territory_markers definition for marker 'TERRITORY_1_ALTISAIR_C'. Deleting it!"
"WARNING: No config_territory_markers definition for marker 'TERRITORY_IRAKLIA_RUINS_1'. Deleting it!"
"Creating territory capture trigger for 'TERRITORY_ORINO_FORTRESS_1'"
"WARNING: No config_territory_markers definition for marker 'TERRITORY_IRAKLIA_RUINS_2'. Deleting it!"
"A3W - 0 baseparts and objects have been saved with iniDBI"
Duplicate weapon CMFlareLauncher detected for O_Heli_Light_02_unarmed_F
Duplicate weapon CMFlareLauncher detected for O_Heli_Light_02_unarmed_F
Strange convex component24 in a3\structures_f\households\house_small02\i_house_small_02_v1_dam_f.p3d:geometryView
Strange convex component57 in a3\structures_f\households\house_small03\i_house_small_03_v1_dam_f.p3d:geometryPhys
"A3W - 0 vehicles have been saved with iniDBI"
"WASTELAND SERVER - 19 Static helis Spawned"

*************** Wrong init state
"pvar_requestPlayerData: [3,R Alpha 1-2:1 (HAVOC) REMOTE,R Alpha 1-2:1 (HAVOC) REMOTE]"

Strange convex component24 in a3\structures_f\households\house_small02\u_house_small_02_v1_dam_f.p3d:geometryView
"-- LOOTSPAWNER Buildingpositions_list ready, d: 21.759s"
"A3W - 0 baseparts and objects have been saved with iniDBI"
"A3W - 0 vehicles have been saved with iniDBI"
"WASTELAND - Vehicle spawning completed - 200 town vehicles spawned in 23.288s"
"WASTELAND SERVER - 2 Planes Spawned"
class HitPoints::HitFuel not found in I_Boat_Armed_01_minigun_F
class HitPoints::HitFuel not found in B_Boat_Armed_01_minigun_F
class HitPoints::HitFuel not found in C_Boat_Civil_01_F
"-- LOOTSPAWNER LSusedclass_list ready, d: 7.347s"
"-- LOOTSPAWNER LSDer started..."
class HitPoints::HitFuel not found in O_Boat_Armed_01_hmg_F
class HitPoints::HitFuel not found in C_Boat_Civil_01_rescue_F

I am still going though the code and know from struggeling the problem is from the server init file loading something but not sure what...if you can help would be very grateful...

thanks
Havoc

**Comment by Firstyminator** [comment]
Little late :)  But i hope you figured it out.  Several codes went to shit when BiS updated Arma that time.  So i've never updated this code,  because Tanoa came :)
